### ISSUE TITLE
array transpose example

### ISSUE THREAD

**Issue by sorenburkhart** [kuleshov/cs228-material#2]
First off, this is a great tutorial on Python and Numpy!  

One issue I saw in the **Array math** section when demonstrating transposing it shows:

```
v = np.array([1,2,3])
print v 
print v.T
```

which results in:

```
[1 2  3]
[1 2  3]
```

Shouldn't it be:

```
v = np.array([[1,2,3]])
print v 
print v.T
```

which results in:

```
[[1 2 3]]
[[1]
 [2]
 [3]]
```

**Comment by kuleshov** [comment]
Yes, that's correct thanks!
