### ISSUE TITLE
Wrong quicksort function

### ISSUE THREAD

**Issue by allenzhao** [kuleshov/cs228-material#7]
In [this section](https://render.githubusercontent.com/view/ipynb?commit=9ccbc1fb00f0a26ec2519d0d90290721a744ae95&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6b756c6573686f762f63733232382d6d6174657269616c2f396363626331666230306630613236656332353139643064393032393037323161373434616539352f7475746f7269616c732f707974686f6e2f63733232382d707974686f6e2d7475746f7269616c2e6970796e62&nwo=kuleshov%2Fcs228-material&path=tutorials%2Fpython%2Fcs228-python-tutorial.ipynb&repository_id=49236094&repository_type=Repository#Basics-of-Python),
the quick sort function was written as:
`    pivot = arr[len(arr) / 2]`, while it should be `        pivot = arr[len(arr) // 2]` according to [the original](http://cs231n.github.io/python-numpy-tutorial/)

**Comment by kuleshov** [comment]
Fixed, thanks!
